export const AUTH = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
}

export const APP = {
    LOADING: 'LOADING',
    BUTTON_LOADING: 'BUTTON_LOADING',

    ERROR_SNACK_OPEN: 'ERROR_SNACK_OPEN',
    ERROR_SNACK_CLOSE: 'ERROR_SNACK_CLOSE',

    SUCCESS_SNACK_OPEN: 'SUCCESS_SNACK_OPEN',
    SUCCESS_SNACK_CLOSE: 'SUCCESS_SNACK_CLOSE',
}

export const CLIENTS = {
    GET_CHAT_HISTORY: 'GET_CHAT_HISTORY',
    GET_CHAT_HISTORY_SUCCESS: 'GET_CHAT_HISTORY_SUCCESS',

    GET_MORE_CHAT_MESSAGES: 'GET_MORE_CHAT_MESSAGES',
    GET_MORE_CHAT_MESSAGES_SUCCESS: 'GET_MORE_CHAT_MESSAGES_SUCCESS',

    GET_NEW_MESSAGE: 'GET_NEW_MESSAGE',

    SEND_MESSAGE: 'SEND_MESSAGE',

    GET_ALL_CHATS: 'GET_ALL_CHATS',
    GET_ALL_CHATS_SUCCESS: 'GET_ALL_CHATS_SUCCESS',

    CREATE_ROOM: 'CREATE_ROOM',

    GET_INVITES: 'GET_INVITES',
    GET_INVITES_SUCCESS: 'GET_INVITES_SUCCESS',

    POST_KEY: 'POST_KEY',

    SAVE_DECRYPTED_STRING: 'SAVE_DECRYPTED_STRING',
    SAVE_DECRYPTED_STRING_SUCCESS: 'SAVE_DECRYPTED_STRING_SUCCESS',
}
