export const AUTH = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
}

export const APP = {
    LOADING: 'LOADING',
    BUTTON_LOADING: 'BUTTON_LOADING',

    ERROR_SNACK_OPEN: 'ERROR_SNACK_OPEN',
    ERROR_SNACK_CLOSE: 'ERROR_SNACK_CLOSE',

    SUCCESS_SNACK_OPEN: 'SUCCESS_SNACK_OPEN',
    SUCCESS_SNACK_CLOSE: 'SUCCESS_SNACK_CLOSE',
}

export const CLIENTS = {
    GET_NEW_MESSAGE: 'GET_NEW_MESSAGE',

    LOAD_ROOM_HISTORY: 'LOAD_ROOM_HISTORY',
    ADD_ROOM_HISTORY: 'ADD_ROOM_HISTORY',
}
